In [2]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import getpass  # To get the password without showing the input
password = getpass.getpass("Please, input your SQL password: ")

# Note that when you use _SQLAlchemy_ and establish the connection, you do not even need to be logged in SQL Pro or MySQL Workbench.
bd = "sakila"
connection_string = 'mysql+pymysql://root:' + password + '@localhost/'+bd
engine = create_engine(connection_string)
engine

Please, input your SQL password:  ········

Engine(mysql+pymysql://root:***@localhost/sakila)

In [3]:
from sqlalchemy import text

In [14]:
def rentals_month(eng,mth, yr):
    with eng.connect() as connection:
        # Getting how many loans were granted every year, and the month of each duration.
        txt = f'select * from rental where month(rental_date) = {mth} and year(rental_date) = {yr};'
        query = text(txt)
        result = connection.execute(query)
        df = pd.DataFrame(result.all())
        return df

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53
...,...,...,...,...,...,...,...
1151,1153,2005-05-31 21:36:44,2725,506,2005-06-10 01:26:44,2,2006-02-15 21:30:53
1152,1154,2005-05-31 21:42:09,2732,59,2005-06-08 16:40:09,1,2006-02-15 21:30:53
1153,1155,2005-05-31 22:17:11,2048,251,2005-06-04 20:27:11,2,2006-02-15 21:30:53
1154,1156,2005-05-31 22:37:34,460,106,2005-06-01 23:02:34,2,2006-02-15 21:30:53
1155,1157,2005-05-31 22:47:45,1449,61,2005-06-02 18:01:45,1,2006-02-15 21:30:53

Develop a Python function called rental_count_month that takes the DataFrame provided by rentals_month as input along 
with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the 
selected month and year.

The function should also include the month and year as parameters and use them to name the new column according to 
the month and year, for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".

In [63]:
def rental_count_month(dataframe,mth,yr):
    results = dataframe.groupby('customer_id')['rental_id'].count()
    results = results.reset_index(name=f'rentals_{mth:02d}_{yr}')
    return results

     customer_id  rentals_12_2005
0              1              649
1              2              320
2              3             1265
3              5             2958
4              6             1550
..           ...              ...
515          594             2736
516          595              613
517          596             4265
518          597              548
519          599             1008

[520 rows x 2 columns]

Create a Python function called compare_rentals that takes two DataFrames as input containing the number of 
rentals made by each customer in different months and years. The function should return a combined DataFrame 
with a new 'difference' column, which is the difference between the number of rentals in the two months.

In [85]:
def compare_rentals(df1,df2):
    df3 = df1.merge(df2)
    df3['difference']= df3.iloc[:,-2]-df3.iloc[:,-1]
    return df3

     customer_id  rentals_05_2005  rentals_12_2005  difference
0              1              649            13763      -13114
1              2              320             2128       -1808
2              3             1265             7811       -6546
3              5             2958            10892       -7934
4              6             1550             7727       -6177
..           ...              ...              ...         ...
507          594             2736            13667      -10931
508          595              613             4541       -3928
509          596             4265             4411        -146
510          597              548             8276       -7728
511          599             1008            12142      -11134

[512 rows x 4 columns]